add_to_db: 1            # 0: recognise sequence only; 1: create database and recognise sequence
gpu:  1                 # use GPU
ncand: 50               # number of candidate images in stage I
stage1: 'netvlad'           # 'vgg' or 'netvlad'
video:
    onscreen: 0         # visualize recognition sequence and save video
    ondisk: 0           # create output video
path_to_ref:  '/data/Datasets/Kudamm_icra/Reference/'
path_to_query: '/data/Datasets/Kudamm_icra/Live/'
ftol: 2                # ground truth frame tolerance (+- frames)

